services:
  n8n:
    image: n8nio/n8n:latest
    user: "1000:1000"
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=false
    volumes:
      - /opt/n8n:/home/node/.n8n
    restart: always
    networks:
      - proxy-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - proxy-net

#  chromadb:
#    image: ghcr.io/abetlen/chroma:latest
#    container_name: chromadb
#    ports:
#      - "8000:8000"
#    volumes:
#      - chroma_data:/chroma
#    restart: always
#    networks:
#      - proxy-net

volumes:
  ollama_data:
  chroma_data:

networks:
  proxy-net:
    external: true
