version: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/mm/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - mm_default
      - n8n-docker_default

networks:
  mm_default:
    external: true
  n8n-docker_default:
    external: true
